import React, {useState} from "react";
import {Alert, Pressable, ScrollView, StyleSheet, Text, TextInput} from "react-native";
import {router} from "expo-router";
import {createVehicle} from "@motoraconect/api";
import {supabase} from "@/lib/supabase";

export default function SellScreen(){
  const [title,setTitle]=useState("");const [make,setMake]=useState("");const [model,setModel]=useState("");const [year,setYear]=useState("");const [price,setPrice]=useState("");const [city,setCity]=useState("");const [description,setDescription]=useState("");const [saving,setSaving]=useState(false);
  const save=async()=>{if(!title.trim()||!make.trim()||!model.trim()||!year||!price){Alert.alert("Missing information","Add title, make, model, year, and price.");return;}setSaving(true);const result=await createVehicle(supabase,{title:title.trim(),make:make.trim(),model:model.trim(),year:Number(year),price_amount:Number(price),city:city.trim()||null,description:description.trim()||null});setSaving(false);if(result.error){Alert.alert("Could not save",result.error.userMessage);return;}Alert.alert("Saved","Your vehicle is saved as a draft.",[{text:"View listing",onPress:()=>router.push(`/(tabs)/vehicles/${result.data.id}`)}]);};
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.heading}>Sell a vehicle</Text><Text style={styles.help}>Start with the core details. Photos, review, and publishing controls build on this draft flow.</Text><TextInput placeholder="Listing title" value={title} onChangeText={setTitle} style={styles.input}/><TextInput placeholder="Make" value={make} onChangeText={setMake} style={styles.input}/><TextInput placeholder="Model" value={model} onChangeText={setModel} style={styles.input}/><TextInput placeholder="Year" value={year} onChangeText={setYear} keyboardType="number-pad" style={styles.input}/><TextInput placeholder="Price (PKR)" value={price} onChangeText={setPrice} keyboardType="decimal-pad" style={styles.input}/><TextInput placeholder="City" value={city} onChangeText={setCity} style={styles.input}/><TextInput placeholder="Description" value={description} onChangeText={setDescription} multiline style={[styles.input,{minHeight:110,textAlignVertical:"top"}]}/><Pressable disabled={saving} style={styles.button} onPress={save}><Text style={styles.buttonText}>{saving?"Saving...":"Save draft"}</Text></Pressable></ScrollView>;
}
const styles=StyleSheet.create({container:{padding:20,gap:12},heading:{fontSize:28,fontWeight:"700"},help:{color:"#666",lineHeight:20},input:{borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:12},button:{padding:14,borderRadius:12,backgroundColor:"#111",alignItems:"center"},buttonText:{color:"#fff",fontWeight:"700"}});